### ISSUE TITLE
.nomad files aren't auto highlighted

### ISSUE THREAD

**Issue by mattleong** [jvirtanen/vim-hcl#17]
However, they will work if I manually run:
`set syntax=hcl`
OR
`set ft=hc`

Looking at `ftdetect/hcl.vim`, shouldn't files with `ft=nomad` be set to hcl syntax? Or am I missing something? 

Thanks!

**Comment by jvirtanen** [comment]
Hi @mattleong! Yes, with this plugin you should end up with the file type `nomad` and the syntax `hcl`. The file type/syntax split is there to improve interoperability with other Vim plugins that might work specifically with either Nomad or Terraform files.

What does `set filetype` say to you on one of these files? What about `set syntax`? Do you use some other Vim plugins that might apply to Nomad files?

**Comment by hanshasselberg** [comment]
`set filetype` says `nomad`. `set syntax` says `nomad` as well.

**Comment by jvirtanen** [comment]
Do you use some other Vim plugins that could perhaps `set syntax=nomad` for `filetype` `nomad`?

**Comment by hanshasselberg** [comment]
Is there a way to find out how that got set?

**Comment by mattleong** [comment]
> Do you use some other Vim plugins that could perhaps `set syntax=nomad` for `filetype` `nomad`?

Confirming that I do not use any other plugins that would do that.

**Comment by jvirtanen** [comment]
Which Vim versions are you two using?

**Comment by jvirtanen** [comment]
> Is there a way to find out how that got set?

Yes, I just learned that there is. Give the command `:verbose set syntax?` to see what last `set syntax`.

**Comment by jvirtanen** [comment]
@mattleong @i0rek Did you test `:verbose set syntax?` to see what last `set syntax` on a Nomad file?

**Comment by orlvn** [comment]
Just to add that the same is happening to me, but for Terraform files (.tf), while Terragrunt (.hcl) are working fine (I don't use Nomad).
  When I manualy set ft=hcl, this is the output of verbose test:
```
  syntax=hcl
        Last set from /usr/share/vim/vim82/syntax/syntax.vim line 32
```
When I just open a .tf file it just says:
```
syntax=
```
And there is no highlighting.

System: MacOS with Apple's Vim v8.2

**Comment by orlvn** [comment]
Oh, and replacing terraform with hcl in ftdetect/hcl.vim:
```
- autocmd BufNewFile,BufRead *.tf      set filetype=terraform
+ autocmd BufNewFile,BufRead *.tf     set filetype=hcl
```
Fixes the issue for .tf files.

**Comment by jvirtanen** [comment]
Thank you for the additional details, @orlvn.

I'm also using Vim 8.2, and unfortunately I still cannot reproduce the issue locally. However, I can see that this issue is affecting many. I believe that this issue originated with the commit https://github.com/jvirtanen/vim-hcl/commit/13020b3a5cc4754cf5dbb6290691e7034ac4629d, which started using different `filetype` and `syntax` values for Nomad and Terraform. This was in response to #14, which was concerned with the compatibility between this plugin and some other plugins that expected `filetype=terraform` rather than `filetype=hcl` for Terraform files.

I will revert that commit for now. I spent some time yesterday studying the built-in plugins in Vim 8.2, and I couldn't find any file formats for which `filetype` and `syntax` didn't match. Therefore I think it's safer to just `set filetype=hcl` (or perhaps start using `setfiletype`, which does not override an earlier settting) also for Nomad and Terraform files.

**Comment by jvirtanen** [comment]
#18 hopefully solved the issue for all of you.

**Comment by dR3b** [comment]
Work perfect! Thanks!!!!
